### PR TITLE
added a pollable receiver function

### PR DESCRIPTION
**Pull request by lwheat**
This change is [Reviewable](https://reviewable.io/reviews/spirentorion/rmq/1)

### CODE REVIEW

**Comment by djoyner** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[queue.go, line 351 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGFmpoT2ZHGajOtiwT:-KJGFmpoT2ZHGajOtiwU:1502629684) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L351)):_

> ``` Go
> 
> // ReceiveBatch tries to read batchSize deliveries, returns true if any and all were received
> func (queue *redisQueue) ReceiveBatch(batchSize int, waitTime time.Duration) ([]Delivery, bool) {
> ```

For the return value, consider `([]Delivery, bool, error)` so that errors aren't hidden.  Also, since the boolean appears to be true whenever the slice is non-empty, I'm not sure what value it really has?  It's pretty easy to deal with empty slices.

---

_[queue.go, line 356 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGHdUHXNlXFfJq0Vc3:-KJGHdUHXNlXFfJq0Vc4:-260007344) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L356)):_

> ``` Go
>   }
> 
>   currentTime := time.Now().UTC()
> ```

Since the time isn't being formatted in a way that the TZ is needed, or used externally in any way there is no need to be explicit with `UTC`.

---

_[queue.go, line 361 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGG3XrQHor5ZGN2l8Y:-KJGG3XrQHor5ZGN2l8Z:-1900608794) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L361)):_

> ``` Go
> 
>   var delivery Delivery
>   batch := []Delivery{}
> ```

Typically this would be `var batch []Delivery`.  No need to create an empty slice.  `append` does the right thing when appending to a `nil`-valued slice.

---

_[queue.go, line 367 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGGX4H35isAYAIOnk5:-KJGGX4H35isAYAIOnk6:1254162923) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L367)):_

> ``` Go
>       // redisErrIsNil may panic because the transport may reuse connections unexpectedly.
>       // instead, perform check in-line and don't panic if Redis has the problem.
>       if err := result.Err(); err == nil {
> ```

Typically this would be a check for `err != nil` and then return.  No need for the else block in the case of no error (reduces nesting).

---

_[queue.go, line 380 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGHOpwI1dRPnEOAbVk:-KJGHOpwI1dRPnEOAbVl:65573728) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L380)):_

> ``` Go
>       if timeRemainingSeconds <= 0 {
>           break
>       }
> ```

Seems like redundant checks in terms of `currentTime.After` and `timeRemainingSeconds <= 0`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/rmq/1)_

**Comment by lwheat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[queue.go, line 351 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGFmpoT2ZHGajOtiwT:-KJGfYljnVqR_1Xm_3xS:-1641535258) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L351)):_
<details><summary>

<i>Previously, djoyner (David Joyner) wrote…</i></summary>



> For the return value, consider `([]Delivery, bool, error)` so that errors aren't hidden.  Also, since the boolean appears to be true whenever the slice is non-empty, I'm not sure what value it really has?  It's pretty easy to deal with empty slices.
> </details>
> ok. Initial implementation followed existing pattern in the package that hides the actual error and returns true/false. I was not a fan. Since the new function is for us, will switch to ([]Delivery, error)

---

_[queue.go, line 356 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGHdUHXNlXFfJq0Vc3:-KJGXlWr1znY6JpL__2v:160415405) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L356)):_
<details><summary>

<i>Previously, djoyner (David Joyner) wrote…</i></summary>



> Since the time isn't being formatted in a way that the TZ is needed, or used externally in any way there is no need to be explicit with `UTC`.
> </details>
> ok.

---

_[queue.go, line 361 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGG3XrQHor5ZGN2l8Y:-KJGfOY77UuMCfTsnur2:160415405) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L361)):_
<details><summary>

<i>Previously, djoyner (David Joyner) wrote…</i></summary>



> Typically this would be `var batch []Delivery`.  No need to create an empty slice.  `append` does the right thing when appending to a `nil`-valued slice.
> </details>
> ok.

---

_[queue.go, line 367 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGGX4H35isAYAIOnk5:-KJGet35Thn4wB5OzHJN:160415405) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L367)):_
<details><summary>

<i>Previously, djoyner (David Joyner) wrote…</i></summary>



> Typically this would be a check for `err != nil` and then return.  No need for the else block in the case of no error (reduces nesting).
> </details>
> ok.

---

_[queue.go, line 380 [r1]](https://reviewable.io:443/reviews/spirentorion/rmq/1#-KJGHOpwI1dRPnEOAbVk:-KJGYiy_IVqHoPAzmU9E:160415405) ([raw file](https://github.com/spirentorion/rmq/blob/d5cddd55c50dcf2b43778025fff5b368a4703eaa/queue.go#L380)):_
<details><summary>

<i>Previously, djoyner (David Joyner) wrote…</i></summary>



> Seems like redundant checks in terms of `currentTime.After` and `timeRemainingSeconds <= 0`.
> </details>
> ok.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/rmq/1)_

**Comment by lwheat** [comment]
Bump.

**Comment by djoyner** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/rmq/1)_

**Pull request merged**
